from pathlib import Path
import json
from playwright.sync_api import sync_playwright
from browser_harness import launch_chromium
ROOT=Path(__file__).resolve().parents[1]
ADMIN=(ROOT/'public/admin.html').read_text(encoding='utf-8')
INLINE_CSS=ADMIN[ADMIN.index('<style>')+7:ADMIN.index('</style>')]
SHELL_CSS=(ROOT/'public/css/admin-shell.css').read_text(encoding='utf-8')
js_start=ADMIN.index('let detailAccountData = null;'); js_end=ADMIN.index('// ============================================================\n// TABS',js_start); DETAIL_JS=ADMIN[js_start:js_end]
MODERN={"accountId":"A-DETAIL-1","name":"Alice","status":"active","accountType":"google","provider":"google","createdAt":"2026-09-24T08:00:00Z","lastSeen":"2026-09-26T05:30:00Z","lastPlayedAt":"2026-09-26T05:00:00Z","joinCount":8,"games":5,"wins":3,"losses":2,"aliases":["Alice-old"],"temporaryExpiresAt":None,"live":[{"roomId":"JRDCR","isHost":False}],"events":[{"type":"game_end","eventKind":"game_end","roomId":"JRDCR","time":"2026-09-26T05:00:00Z","role":"ชาวบ้าน","won":True,"left":False},{"type":"room_join","eventKind":"room_join","roomId":"JRDCR","time":"2026-09-26T04:30:00Z","won":None,"left":False},{"type":"game_end","eventKind":"game_end","roomId":"ABC12","time":"2026-09-25T05:00:00Z","role":"หมาป่า","won":False,"left":False},{"type":"game_leave","eventKind":"game_leave","roomId":"ABC12","time":"2026-09-25T04:45:00Z","left":True,"leaveReason":"new_room","won":None}]}
LEGACY={"name":"Legacy User","legacy":True,"status":"legacy","firstSeen":"2026-09-20T08:00:00Z","lastSeen":"2026-09-26T03:00:00Z","joinCount":2,"games":2,"wins":1,"losses":1,"winRate":50,"aliases":[],"events":[{"type":"game_end","eventKind":"game_end","roomId":"LEG01","time":"2026-09-25T01:00:00Z","role":None,"won":True,"left":False}]}

def fixture_html():
    helpers=r'''
    window.escapeHtml=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
    window.formatDateTime=(iso)=>iso?new Date(iso).toLocaleString('th-TH',{timeZone:'UTC'}):'-';
    window.statusLabel=(s)=>({active:'ปกติ',suspended:'พักบัญชี',deleted:'ลบบัญชี',legacy:'ข้อมูลเก่า'})[s]||s||'-';
    window.detailAccountId=''; window.detailLegacyName=''; window.wwConfirm=async()=>true; window.wwAlert=()=>{}; window.wwToast=()=>{}; window.socket={emit:()=>{}}; window.loadAllPlayers=()=>{}; window.loadAccounts=()=>{}; window.refreshDashboard=()=>{}; window.WWAdminShell={setContext:()=>{}}; window.currentTab='all'; window.switchTab=()=>{}; window.closeRoomInspector=()=>{}; window.setAdminPageHeader=()=>{};
    '''
    return f'''<!doctype html><html lang="th"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>{SHELL_CSS}\n{INLINE_CSS}</style></head><body data-page="admin"><div class="admin-app-shell"><header class="admin-topbar" style="height:72px;flex:0 0 72px"><div>ADMIN</div></header><div class="admin-layout-grid" style="height:calc(100dvh - 72px);grid-template-columns:minmax(0,1fr)"><main class="admin-workspace" style="padding:12px"><div class="admin-page-stack"><section id="playerDirectoryView" class="admin-list-view"><div>LIST</div></section><section id="playerDetailWorkspace" class="admin-detail-workspace hidden" aria-hidden="true"><div class="admin-detail-breadcrumb"><button type="button" data-player-detail-back>ผู้เล่น</button><span>›</span><strong id="playerDetailBreadcrumbName">รายละเอียดผู้เล่น</strong></div><div class="admin-detail-header"><div><span class="admin-detail-kicker">PLAYER DETAIL</span><h2>👤 <span id="playerDetailHeaderName">รายละเอียดผู้เล่น</span></h2><p id="playerDetailHeaderSub"></p><div class="admin-detail-header-meta"><span id="playerDetailHeaderId"></span><span id="playerDetailHeaderStatus"></span></div></div><div class="admin-detail-header-actions"><button type="button" class="btn" data-player-detail-back>กลับ</button><button type="button" class="btn" data-player-detail-refresh>รีเฟรช</button></div></div><div class="admin-detail-body" id="accountDetailBody"><div class="hist-empty">กำลังโหลด...</div></div></section></div></main></div></div><script>{helpers}</script><script>{DETAIL_JS}</script></body></html>'''

def main():
    with sync_playwright() as p:
        browser=launch_chromium(p); page=browser.new_page(viewport={'width':1180,'height':682}); errors=[]; page.on('pageerror',lambda e:errors.append(str(e))); page.set_content(fixture_html(),wait_until='domcontentloaded'); page.wait_for_timeout(50); assert not errors,errors
        page.evaluate('window.setPlayerDetailWorkspaceVisible(true); window.renderModernAccountDetail(%s)'%json.dumps(MODERN,ensure_ascii=False)); assert page.locator('#playerDetailWorkspace').is_visible(); assert page.locator('#playerDirectoryView').is_hidden(); assert page.locator('#playerDetailHeaderName').inner_text().strip() == 'Alice'; assert page.locator('#playerDetailHeaderId').inner_text().strip() == 'A-DETAIL-1'; assert page.locator('#playerDetailHeaderStatus .mini-tag').count() == 2; assert page.locator('.account-kpi').count()==4; assert page.locator('.account-detail-section').count()==2; assert page.locator('.account-detail-action-panel').count()==1
        page.locator('[data-detail-action="history"]').click(); assert page.locator('.account-history-view').count()==1; assert page.locator('.account-history-topic').count()==4; assert page.locator('.account-history-topic.is-open').count()==0; page.locator('[data-history-topic="games"]').click(); assert page.locator('.account-history-topic.is-open').count()==1; page.locator('[data-history-topic="rooms"]').click(); assert page.locator('.account-history-topic.is-open').count()==1; page.locator('.account-history-back').click(); assert page.locator('#playerDetailHeaderName').inner_text().strip() == 'Alice'
        page.evaluate('window.renderLegacyAccountDetail(%s)'%json.dumps(LEGACY,ensure_ascii=False)); assert page.locator('[data-detail-action="migrate-legacy"]').count()==1; assert page.locator('[data-detail-action="delete-legacy"]').count()==1
        page.locator('[data-player-detail-back]').first.click(); assert page.locator('#playerDirectoryView').is_visible() and page.locator('#playerDetailWorkspace').is_hidden()
        page.evaluate('window.setPlayerDetailWorkspaceVisible(true); window.renderModernAccountDetail(%s)'%json.dumps(MODERN,ensure_ascii=False)); page.wait_for_timeout(20)
        for width,height in [(390,844),(1180,682),(1440,900),(1800,1000)]:
            page.set_viewport_size({'width':width,'height':height}); page.wait_for_timeout(20); d=page.locator('#playerDetailWorkspace').bounding_box(); w=page.locator('.admin-workspace').bounding_box(); t=page.locator('.admin-topbar').bounding_box(); inner=page.locator('.admin-workspace').evaluate("e=>e.clientWidth-parseFloat(getComputedStyle(e).paddingLeft)-parseFloat(getComputedStyle(e).paddingRight)"); overflow=page.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth'); assert d and w and t and d['width']>=inner-2 and d['y'] >= t['y'] + t['height'] - 1,(width,height,d,w,t,inner); assert overflow<=1,(width,height,overflow)
        browser.close()
    print('admin-player-detail-history-regression: PASS')
if __name__=='__main__': main()
